<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="用户管理系统测试套件" duration-ms="816" started-at="2018-11-30T06:16:48Z" finished-at="2018-11-30T06:16:48Z">
    <groups>
      <group name="loginTrue">
        <method signature="LoginTest.loginTrue()[pri:0, instance:com.test.jenkins.cases.LoginTest@4f933fd1]" name="loginTrue" class="com.test.jenkins.cases.LoginTest"/>
      </group> <!-- loginTrue -->
      <group name="loginFalse">
        <method signature="LoginTest.loginFalse()[pri:0, instance:com.test.jenkins.cases.LoginTest@4f933fd1]" name="loginFalse" class="com.test.jenkins.cases.LoginTest"/>
      </group> <!-- loginFalse -->
    </groups>
    <test name="用户管理系统测试用例" duration-ms="816" started-at="2018-11-30T06:16:48Z" finished-at="2018-11-30T06:16:48Z">
      <class name="com.test.jenkins.cases.LoginTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.test.jenkins.cases.LoginTest@4f933fd1]" name="beforeTest" is-config="true" duration-ms="50" started-at="2018-11-30T14:16:48Z" description="测试准备工作，获取HttpClient对象" finished-at="2018-11-30T14:16:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="loginTrue()[pri:0, instance:com.test.jenkins.cases.LoginTest@4f933fd1]" name="loginTrue" duration-ms="690" started-at="2018-11-30T14:16:48Z" description="用户登陆成功接口测试" finished-at="2018-11-30T14:16:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTrue -->
        <test-method status="FAIL" signature="loginFalse()[pri:0, instance:com.test.jenkins.cases.LoginTest@4f933fd1]" name="loginFalse" duration-ms="44" started-at="2018-11-30T14:16:48Z" description="用户登陆失败接口测试" finished-at="2018-11-30T14:16:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.jenkins.cases.LoginTest.loginFalse(LoginTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFalse -->
      </class> <!-- com.test.jenkins.cases.LoginTest -->
    </test> <!-- 用户管理系统测试用例 -->
  </suite> <!-- 用户管理系统测试套件 -->
</testng-results>
